import '@/styles/globals.css';
import '@/styles/body-before.css';
import '@mantine/core/styles.css';
import '@mantine/code-highlight/styles.css';

import { ColorSchemeScript } from '@mantine/core';
import { clsx } from 'clsx';

import { baloo2, firaCode, notoSansJP } from '@/styles/fontFamilies';

import { AppLayout } from './layout/index';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <head>
        <ColorSchemeScript defaultColorScheme="light" />
      </head>
      <body
        className={clsx([
          baloo2.variable,
          firaCode.variable,
          notoSansJP.variable,
        ])}
      >
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
